config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
    #get "characters", to: "characters#index"
  root to: "pages#home"
  resources :characters
  get "ruta1", to:"characters#ruta1"
  get "ruta2", to:"characters#ruta2"
  get "ruta3", to:"characters#ruta3"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  def index
    @characters = Character.all
    #@characters = [0x0111,0x0a222,0x0b0003]
  end

  def show
    @character = Character.find(params[:id])
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)
    @character.save
    redirect_to character_path(@character)
  end

  def edit
    @character = Character.find(params[:id])
  end

  def update
    @character = Character.find(params[:id])
    @character.update(character_params)
    redirect_to character_path(@character)
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy
    redirect_to character_path, status: :see_other
  end

  def ruta1
  end

  def ruta2
  end

  def ruta3
  end

  private

  def character_params
    params.require(:character).permit(:name, :actor, :review, :image_url)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @characters = Character.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/characters/edit.html.erb
<%= form_with model: @character do |f| %>
  <%= f.label :name %>
  <%= f.text_field :review %>
  <%= f.label :actor %>
  <%= f.label :image_url %>
  <%= f.submit %>
<% end %>

app/views/characters/index.html.erb
<h1>Welcome to the Harry Potter App</h1>
<% @characters.each do |character| %>
  <%= character.name %></li>
<% end %>

app/views/characters/new.html.erb
<%= form_with model: @character do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :review %>
  <%= f.text_field :review %>
  <%= f.label :actor %>
  <%= f.text_field :actor %>
  <%# <%= f. :image_url %>
  <%= f.submit %>
<% end %>

app/views/characters/ruta1.html.erb
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Quiz</title>
    <link rel="stylesheet" href="css/styles.css">
    <link href='https://fonts.googleapis.com/css?family=Crimson+Text' rel='stylesheet' type='text/css'>
</head>
<body>

    <div class="container">

        <header>
            <div class="center">
                <h1>Harry Potter Quiz</h1>
            </div>
        </header>

        <section id="instructions" class="center">
            <h2>How big of a fan do you think you are?</h2>
            <h3>Test your Harry Potter knowledge and see where you stand.</h3>
            <button id="startBtn">Start</button>
        </section>

        <section id="quiz">
            <div>
                <h3 class="left">Score:  <span id="displayScore">0</span></h3>
                <h3 class="right">Question: <span id="displayQCount">1</span> of  5</h3>
            </div>
            <div>
                <h2 id="askQuestion" class="center"></h2>

                <form id="form">
                    <div>
                        <input id="label0" type="radio" name="option" value="">
                        <label id="answer0" for=""></label>
                    </div>
                    <div>
                        <input id="label1" type="radio" name="option" value="">
                        <label id="answer1" for=""></label>
                    </div>
                    <div>
                        <input id="label2" type="radio" name="option" value="">
                        <label id="answer2" for=""></label>
                    </div>
                    <div>
                        <input id="label3" type="radio" name="option" value="">
                        <label id="answer3" for=""></label>
                    </div>
                </form>

            <button id="submitBtn">Submit</button>
            </div>
        </section>

        <section id="showScore">
            <h2 id="inform" class="center"></h2>
            <button id="resetBtn">Try Again?</button>
        </section>

    </div>

<!-- JavaScript -->
<script src="js/scripts.js"></script>
</body>
</html>

app/views/characters/show.html.erb
<h1>Personaje:</h1>
<%= @character.name %>
<%= @character.actor %>
<%= @character.review %>
<img src="<%= @character.image_url %>" alt="">


<%= link_to "Delete",
  character_path(@rcharacter),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HarryPotterApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <%= render "shared/navbar" %>
    <%= yield %>
  <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="symbol">
  <div class="deathly"></div>
  <div class="hallows"></div>
</div>
<h1>H<i class="fa fa-bolt" aria-hidden="true"></i>P</h1>

<h2><%= link_to "Characters", characters_path %></h2>
<h2>Marauder's Map</h2>
<h2>Learn the spells</h2>
<h2>Wizarding World</h2>

https://www.wizardingworld.com

app/views/shared/_footer.html.erb
<%# <div class="justify-content-right">
  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
    </div>
    <div class="footer-copyright">
      Made with much much <i class="fas fa-heart"></i>.
    </div>
  </div>
</div> %>